/**
 * HTML Exporter Tests
 */

import { assertEquals, assertStringIncludes } from "@std/assert";
import { escapeHtml, exportAsHTML } from "./html-exporter.ts";
import type { ExportOptions } from "./types.ts";

Deno.test("exportAsHTML: 有効なHTMLを生成", () => {
  const options: ExportOptions = {
    html: "<h1>Test</h1><p>Content</p>",
    themeId: "light",
    themeCss: "body { color: black; }",
    title: "Test Document",
  };

  const result = exportAsHTML(options);

  assertStringIncludes(result, "<!DOCTYPE html>");
  assertStringIncludes(result, '<html lang="en">');
  assertStringIncludes(result, "</html>");
  assertStringIncludes(result, '<meta charset="UTF-8">');
  assertStringIncludes(result, '<meta name="viewport"');
  assertStringIncludes(
    result,
    '<meta name="generator" content="Markdown Viewer',
  );
  assertStringIncludes(result, "<title>Test Document</title>");
  assertStringIncludes(result, "<h1>Test</h1>");
  assertStringIncludes(result, "<p>Content</p>");
});

Deno.test("exportAsHTML: テーマCSSを埋め込み", () => {
  const themeCss = "body { background: #fff; color: #000; }";
  const options: ExportOptions = {
    html: "<p>Test</p>",
    themeId: "light",
    themeCss,
  };

  const result = exportAsHTML(options);

  assertStringIncludes(result, "<style>");
  assertStringIncludes(result, themeCss);
  assertStringIncludes(result, "</style>");
});

Deno.test("exportAsHTML: タイトルをエスケープ（XSS対策）", () => {
  const maliciousTitle = '<script>alert("XSS")</script>';
  const options: ExportOptions = {
    html: "<p>Test</p>",
    themeId: "dark",
    themeCss: "body { color: white; }",
    title: maliciousTitle,
  };

  const result = exportAsHTML(options);

  assertStringIncludes(
    result,
    "&lt;script&gt;alert(&quot;XSS&quot;)&lt;/script&gt;",
  );
  assertEquals(result.includes('<script>alert("XSS")</script>'), false);
});

Deno.test("exportAsHTML: メタデータを含める", () => {
  const options: ExportOptions = {
    html: "<p>Test</p>",
    themeId: "github",
    themeCss: "body { color: #24292e; }",
    title: "Test",
    metadata: {
      author: "John Doe",
      description: "A test document",
    },
  };

  const result = exportAsHTML(options);

  assertStringIncludes(result, '<meta name="author" content="John Doe">');
  assertStringIncludes(
    result,
    '<meta name="description" content="A test document">',
  );
});

Deno.test("exportAsHTML: メタデータのXSS対策", () => {
  const options: ExportOptions = {
    html: "<p>Test</p>",
    themeId: "minimal",
    themeCss: "body { color: #333; }",
    metadata: {
      author: '<img src=x onerror="alert(1)">',
      description: "<script>evil()</script>",
    },
  };

  const result = exportAsHTML(options);

  assertStringIncludes(
    result,
    "&lt;img src=x onerror=&quot;alert(1)&quot;&gt;",
  );
  assertStringIncludes(result, "&lt;script&gt;evil()&lt;/script&gt;");
  assertEquals(result.includes('<img src=x onerror="alert(1)">'), false);
  assertEquals(result.includes("<script>evil()</script>"), false);
});

Deno.test("exportAsHTML: スタンドアロンで動作するHTML生成", () => {
  const options: ExportOptions = {
    html: "<h1>Standalone</h1>",
    themeId: "solarized-light",
    themeCss: "body { background: #fdf6e3; }",
    title: "Standalone Test",
  };

  const result = exportAsHTML(options);

  assertStringIncludes(result, "<!DOCTYPE html>");
  assertStringIncludes(result, "<style>");
  assertStringIncludes(result, "body { background: #fdf6e3; }");
  assertStringIncludes(result, "max-width: 900px;");
  assertStringIncludes(result, "@media print");
  assertStringIncludes(
    result,
    'class="markdown-viewer-theme-solarized-light"',
  );
  assertStringIncludes(result, "Generated by");
  assertStringIncludes(result, "Markdown Viewer");
});

Deno.test("exportAsHTML: デフォルトタイトル", () => {
  const options: ExportOptions = {
    html: "<p>Test</p>",
    themeId: "light",
    themeCss: "body { color: black; }",
  };

  const result = exportAsHTML(options);

  assertStringIncludes(result, "<title>Markdown Document</title>");
});

Deno.test("exportAsHTML: Mermaid SVGが埋め込まれたHTMLを正しく出力", () => {
  const mermaidSvg =
    '<div class="mermaid-diagram" data-mermaid-code="graph TD; A-->B;" data-mermaid-rendered="true">' +
    '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="100">' +
    '<g><rect x="0" y="0" width="100" height="50" fill="#f9f9f9"/>' +
    '<text x="50" y="25">A</text></g></svg></div>';

  const options: ExportOptions = {
    html: `<h1>Mermaid Test</h1>${mermaidSvg}`,
    themeId: "light",
    themeCss: "body { color: black; }",
    title: "Mermaid Document",
  };

  const result = exportAsHTML(options);

  assertStringIncludes(result, "<svg");
  assertStringIncludes(result, "mermaid-diagram");
  assertStringIncludes(result, 'data-mermaid-rendered="true"');
  assertStringIncludes(result, "graph TD; A-->B;");
});

Deno.test("exportAsHTML: MathJax SVGが埋め込まれたHTMLを正しく出力", () => {
  const mathjaxSvg =
    '<mjx-container class="MathJax" jax="SVG" display="true">' +
    '<svg xmlns="http://www.w3.org/2000/svg" width="5em" height="2em">' +
    '<g stroke="currentColor" fill="currentColor">' +
    "<text>E=mc²</text></g></svg></mjx-container>";

  const options: ExportOptions = {
    html: `<p>Einstein's equation:</p>${mathjaxSvg}`,
    themeId: "dark",
    themeCss: "body { color: white; }",
    title: "Math Document",
  };

  const result = exportAsHTML(options);

  assertStringIncludes(result, "mjx-container");
  assertStringIncludes(result, "<svg");
  assertStringIncludes(result, "E=mc²");
});

Deno.test("exportAsHTML: Base64画像が埋め込まれたHTMLを正しく出力", () => {
  const base64Img =
    '<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==" alt="test">';

  const options: ExportOptions = {
    html: `<h1>Image Test</h1>${base64Img}`,
    themeId: "github",
    themeCss: "body { color: #24292e; }",
    title: "Image Document",
  };

  const result = exportAsHTML(options);

  assertStringIncludes(result, "data:image/png;base64,");
  assertStringIncludes(result, 'alt="test"');
});

Deno.test("exportAsHTML: Mermaid SVG + MathJax SVG + Base64画像の複合テスト", () => {
  const html = [
    "<h1>Full Export Test</h1>",
    '<div class="mermaid-diagram" data-mermaid-code="graph LR; X-->Y;" data-mermaid-rendered="true"><svg><text>diagram</text></svg></div>',
    '<mjx-container class="MathJax" jax="SVG"><svg><text>x²+y²=z²</text></svg></mjx-container>',
    '<img src="data:image/png;base64,ABC123" alt="embedded">',
    '<img src="https://example.com/remote.png" alt="remote">',
  ].join("\n");

  const options: ExportOptions = {
    html,
    themeId: "minimal",
    themeCss: "body { color: #333; }",
    title: "Full Test",
  };

  const result = exportAsHTML(options);

  assertStringIncludes(result, "mermaid-diagram");
  assertStringIncludes(result, "mjx-container");
  assertStringIncludes(result, "data:image/png;base64,ABC123");
  assertStringIncludes(result, "https://example.com/remote.png");
  assertStringIncludes(result, "<!DOCTYPE html>");
  assertStringIncludes(result, "<title>Full Test</title>");
});

Deno.test("escapeHtml: 基本的なエスケープ", () => {
  assertEquals(escapeHtml("&"), "&amp;");
  assertEquals(escapeHtml("<"), "&lt;");
  assertEquals(escapeHtml(">"), "&gt;");
  assertEquals(escapeHtml('"'), "&quot;");
  assertEquals(escapeHtml("'"), "&#039;");
});

Deno.test("escapeHtml: 複数文字のエスケープ", () => {
  const input = '<script>alert("XSS & injection")</script>';
  const expected =
    "&lt;script&gt;alert(&quot;XSS &amp; injection&quot;)&lt;/script&gt;";
  assertEquals(escapeHtml(input), expected);
});

Deno.test("escapeHtml: 通常の文字列はそのまま", () => {
  const input = "Hello World 123";
  assertEquals(escapeHtml(input), input);
});
