/**
 * HTML Export Logic
 *
 * レンダリング済みHTMLをスタンドアロンHTMLファイルに変換する。
 * テーマCSS、フォント、メタデータを全て1ファイルに埋め込み。
 */

import type { ExportOptions } from "./types.ts";

/**
 * スタンドアロンHTMLを生成
 *
 * テーマCSS、フォント、全てを1ファイルに埋め込み
 * ブラウザで直接開けるHTMLを生成
 *
 * @param options - エクスポートオプション
 * @returns スタンドアロンHTML文字列
 */
export const exportAsHTML = (options: ExportOptions): string => {
  const {
    html,
    themeId,
    themeCss,
    title = "Markdown Document",
    metadata,
  } = options;

  const escapedTitle = escapeHtml(title);
  const authorMeta = metadata?.author
    ? `<meta name="author" content="${escapeHtml(metadata.author)}">`
    : "";
  const descriptionMeta = metadata?.description
    ? `<meta name="description" content="${escapeHtml(metadata.description)}">`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="generator" content="Markdown Viewer - Simple & Secure">
  ${authorMeta}
  ${descriptionMeta}
  <title>${escapedTitle}</title>

  <!-- Theme Styles -->
  <style>
    ${themeCss}
  </style>

  <!-- Export-specific styles (after theme CSS to ensure proper cascade) -->
  <style>
    /* Export-specific layout */
    body {
      max-width: 900px;
      margin: 0 auto;
      padding: 2rem;
      background: var(--markdown-viewer-layout-bg, #ffffff);
      color: var(--markdown-viewer-color, #0d1117);
    }

    /* ToC用のレイアウトをリセット（スタンドアロンHTMLにはToCがない） */
    .markdown-viewer-layout {
      background: transparent !important;
    }

    .markdown-viewer {
      margin-left: 0 !important;
      max-width: 100% !important;
      padding: 0 !important;
    }

    /* Print styles */
    @media print {
      body {
        max-width: 100%;
        padding: 0;
      }
    }
  </style>
</head>
<body class="markdown-viewer-theme-${themeId}">
  <div class="markdown-viewer">
    <div class="markdown-body">
      ${html}
    </div>
  </div>

  <!-- Metadata -->
  <footer style="margin-top: 4rem; padding-top: 2rem; border-top: 1px solid #e5e7eb; font-size: 0.875rem; color: #6b7280;">
    <p>Generated by <a href="https://github.com/ba0918/markdown-viewer" style="color: #2563eb;">Markdown Viewer</a></p>
  </footer>
</body>
</html>`;
};

/**
 * HTMLエスケープ（XSS対策）
 *
 * タイトルやメタデータをエスケープして、XSS攻撃を防ぐ
 *
 * @param text - エスケープする文字列
 * @returns エスケープされた文字列
 */
export const escapeHtml = (text: string): string => {
  const map: Record<string, string> = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
};
