/**
 * HTML Exporter Tests
 */

import { assertEquals, assertStringIncludes } from "@std/assert";
import { escapeHtml, exportAsHTML } from "./html-exporter.ts";
import type { ExportOptions } from "./types.ts";

Deno.test("exportAsHTML: 有効なHTMLを生成", () => {
  const options: ExportOptions = {
    html: "<h1>Test</h1><p>Content</p>",
    themeId: "light",
    themeCss: "body { color: black; }",
    title: "Test Document",
  };

  const result = exportAsHTML(options);

  // DOCTYPE宣言
  assertStringIncludes(result, "<!DOCTYPE html>");

  // HTML構造
  assertStringIncludes(result, '<html lang="en">');
  assertStringIncludes(result, "</html>");

  // メタタグ
  assertStringIncludes(result, '<meta charset="UTF-8">');
  assertStringIncludes(result, '<meta name="viewport"');
  assertStringIncludes(
    result,
    '<meta name="generator" content="Markdown Viewer',
  );

  // タイトル
  assertStringIncludes(result, "<title>Test Document</title>");

  // コンテンツ
  assertStringIncludes(result, "<h1>Test</h1>");
  assertStringIncludes(result, "<p>Content</p>");
});

Deno.test("exportAsHTML: テーマCSSを埋め込み", () => {
  const themeCss = "body { background: #fff; color: #000; }";
  const options: ExportOptions = {
    html: "<p>Test</p>",
    themeId: "light",
    themeCss,
  };

  const result = exportAsHTML(options);

  // CSS埋め込み確認
  assertStringIncludes(result, "<style>");
  assertStringIncludes(result, themeCss);
  assertStringIncludes(result, "</style>");
});

Deno.test("exportAsHTML: タイトルをエスケープ（XSS対策）", () => {
  const maliciousTitle = '<script>alert("XSS")</script>';
  const options: ExportOptions = {
    html: "<p>Test</p>",
    themeId: "dark",
    themeCss: "body { color: white; }",
    title: maliciousTitle,
  };

  const result = exportAsHTML(options);

  // スクリプトタグがエスケープされていること
  assertStringIncludes(
    result,
    "&lt;script&gt;alert(&quot;XSS&quot;)&lt;/script&gt;",
  );

  // 実際のスクリプトタグは含まれていないこと
  assertEquals(result.includes('<script>alert("XSS")</script>'), false);
});

Deno.test("exportAsHTML: メタデータを含める", () => {
  const options: ExportOptions = {
    html: "<p>Test</p>",
    themeId: "github",
    themeCss: "body { color: #24292e; }",
    title: "Test",
    metadata: {
      author: "John Doe",
      description: "A test document",
    },
  };

  const result = exportAsHTML(options);

  // メタデータ確認
  assertStringIncludes(result, '<meta name="author" content="John Doe">');
  assertStringIncludes(
    result,
    '<meta name="description" content="A test document">',
  );
});

Deno.test("exportAsHTML: メタデータのXSS対策", () => {
  const options: ExportOptions = {
    html: "<p>Test</p>",
    themeId: "minimal",
    themeCss: "body { color: #333; }",
    metadata: {
      author: '<img src=x onerror="alert(1)">',
      description: "<script>evil()</script>",
    },
  };

  const result = exportAsHTML(options);

  // エスケープされていること
  assertStringIncludes(
    result,
    "&lt;img src=x onerror=&quot;alert(1)&quot;&gt;",
  );
  assertStringIncludes(result, "&lt;script&gt;evil()&lt;/script&gt;");

  // 実際のタグは含まれていないこと
  assertEquals(result.includes('<img src=x onerror="alert(1)">'), false);
  assertEquals(result.includes("<script>evil()</script>"), false);
});

Deno.test("exportAsHTML: スタンドアロンで動作するHTML生成", () => {
  const options: ExportOptions = {
    html: "<h1>Standalone</h1>",
    themeId: "solarized-light",
    themeCss: "body { background: #fdf6e3; }",
    title: "Standalone Test",
  };

  const result = exportAsHTML(options);

  // スタンドアロン要件チェック
  assertStringIncludes(result, "<!DOCTYPE html>"); // 完全なHTML
  assertStringIncludes(result, "<style>"); // CSS埋め込み
  assertStringIncludes(result, "body { background: #fdf6e3; }"); // テーマCSS
  assertStringIncludes(result, "max-width: 900px;"); // Export固有スタイル
  assertStringIncludes(result, "@media print"); // 印刷スタイル

  // テーマクラス
  assertStringIncludes(
    result,
    'class="markdown-viewer-theme-solarized-light"',
  );

  // フッター
  assertStringIncludes(result, "Generated by");
  assertStringIncludes(result, "Markdown Viewer");
});

Deno.test("exportAsHTML: デフォルトタイトル", () => {
  const options: ExportOptions = {
    html: "<p>Test</p>",
    themeId: "light",
    themeCss: "body { color: black; }",
    // title未指定
  };

  const result = exportAsHTML(options);

  // デフォルトタイトル確認
  assertStringIncludes(result, "<title>Markdown Document</title>");
});

Deno.test("escapeHtml: 基本的なエスケープ", () => {
  assertEquals(escapeHtml("&"), "&amp;");
  assertEquals(escapeHtml("<"), "&lt;");
  assertEquals(escapeHtml(">"), "&gt;");
  assertEquals(escapeHtml('"'), "&quot;");
  assertEquals(escapeHtml("'"), "&#039;");
});

Deno.test("escapeHtml: 複数文字のエスケープ", () => {
  const input = '<script>alert("XSS & injection")</script>';
  const expected =
    "&lt;script&gt;alert(&quot;XSS &amp; injection&quot;)&lt;/script&gt;";
  assertEquals(escapeHtml(input), expected);
});

Deno.test("escapeHtml: 通常の文字列はそのまま", () => {
  const input = "Hello World 123";
  assertEquals(escapeHtml(input), input);
});
